### ISSUE TITLE
refreshing of snippets during search query is confusing and annoying

### ISSUE THREAD

**Issue by julianafreire** [VIDA-NYU/domain_discovery_tool#42]
It is confusing (and annoying) when the query results are being retrieved and their order keeps changing on the screen.

This is a problem especially when we start to label pages, and their snippets keep moving.

Can we "fix" the order at least for the first page? (E.g., once we have the first 12 URLs, show them in first search result page, and leave them there)

**Comment by yamsgithub** [comment]
Hi Juliana:

I think I figured out the problem and it is mostly solved. The problem was
that we were returning the results from elasticsearch(es) as a dictionary
with the id of the page as the key. Dictionaries of course do not maintain
the order of the pages. That is why we saw so many out of synch snippet
updates. So ideally on the client we should be ordering them by some
criteria timestamp or rank.

Added to this is the fact that es pagination does a sort of the index
across shards and sends the results corresponding to the page number.
Unfortunately the timestamp that we store seems to be out of synch with the
criteria that es is using to sort the pages. So I have now added an "order"
field to the pages sent to the client. I am using this field to order the
pages on the client and it seems to be working.

I have checked in the fixes and am in the process of pushing the new docker
image. Would be great if you could test it.

Thanks
Yamuna

**Comment by yamsgithub** [comment]
This was fixed by commit to DD API ViDA-NYU/domain_discovery_API@be1e399
